# Generated by Django 5.2.16 on 2026-08-03 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0041_alter_pageurl_unique_together_pageurl_site_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('heading', models.CharField(blank=True, max_length=120, verbose_name='заголовок')),
                ('subheading', models.CharField(blank=True, max_length=240, verbose_name='подзаголовок')),
                ('anchor', models.SlugField(blank=True, help_text='Используется как id секции для навигации по странице.', max_length=60, verbose_name='якорь')),
                ('text_source', models.CharField(choices=[('summary', 'Краткое описание'), ('biography', 'Расширенное описание')], default='biography', max_length=20, verbose_name='источник текста')),
                ('show_avatar', models.BooleanField(default=True, verbose_name='показывать фотографию')),
                ('show_facts', models.BooleanField(default=True, verbose_name='показывать блок фактов')),
            ],
            options={
                'verbose_name': 'блок «Обо мне»',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='порядок')),
                ('title', models.CharField(max_length=180, verbose_name='название')),
                ('issuer', models.CharField(max_length=160, verbose_name='организация')),
                ('issued_on', models.DateField(verbose_name='дата выдачи')),
                ('url', models.URLField(blank=True, verbose_name='ссылка')),
            ],
            options={
                'verbose_name': 'сертификат',
                'verbose_name_plural': 'сертификаты',
                'ordering': ('order', '-issued_on'),
            },
        ),
        migrations.CreateModel(
            name='DeveloperProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('full_name', models.CharField(max_length=120, verbose_name='полное имя')),
                ('nickname', models.CharField(blank=True, max_length=60, verbose_name='псевдоним')),
                ('headline', models.CharField(max_length=200, verbose_name='специализация')),
                ('summary', models.TextField(max_length=500, verbose_name='краткое описание')),
                ('biography', models.TextField(blank=True, verbose_name='расширенное описание')),
                ('avatar', models.ImageField(blank=True, upload_to='profile/', verbose_name='фотография')),
                ('location', models.CharField(blank=True, max_length=120, verbose_name='местоположение')),
                ('is_available', models.BooleanField(default=True, verbose_name='открыт к предложениям')),
                ('availability_note', models.CharField(blank=True, max_length=160, verbose_name='комментарий о доступности')),
                ('resume_url', models.URLField(blank=True, verbose_name='ссылка на резюме')),
                ('public_email', models.EmailField(blank=True, max_length=254, verbose_name='публичный email')),
                ('cta_text', models.CharField(blank=True, max_length=120, verbose_name='текст призыва к действию')),
                ('cta_url', models.CharField(blank=True, max_length=200, verbose_name='ссылка призыва к действию')),
            ],
            options={
                'verbose_name': 'профиль разработчика',
                'verbose_name_plural': 'профиль разработчика',
            },
        ),
        migrations.CreateModel(
            name='EducationPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('heading', models.CharField(blank=True, max_length=120, verbose_name='заголовок')),
                ('subheading', models.CharField(blank=True, max_length=240, verbose_name='подзаголовок')),
                ('anchor', models.SlugField(blank=True, help_text='Используется как id секции для навигации по странице.', max_length=60, verbose_name='якорь')),
                ('limit', models.PositiveSmallIntegerField(default=5, verbose_name='максимум записей')),
                ('show_certificates', models.BooleanField(default=False, verbose_name='показывать сертификаты')),
            ],
            options={
                'verbose_name': 'блок образования',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ExperiencePluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('heading', models.CharField(blank=True, max_length=120, verbose_name='заголовок')),
                ('subheading', models.CharField(blank=True, max_length=240, verbose_name='подзаголовок')),
                ('anchor', models.SlugField(blank=True, help_text='Используется как id секции для навигации по странице.', max_length=60, verbose_name='якорь')),
                ('limit', models.PositiveSmallIntegerField(default=5, verbose_name='максимум записей')),
                ('show_technologies', models.BooleanField(default=True, verbose_name='показывать технологии')),
            ],
            options={
                'verbose_name': 'блок опыта работы',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='FeaturedSkillsPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('heading', models.CharField(blank=True, max_length=120, verbose_name='заголовок')),
                ('subheading', models.CharField(blank=True, max_length=240, verbose_name='подзаголовок')),
                ('anchor', models.SlugField(blank=True, help_text='Используется как id секции для навигации по странице.', max_length=60, verbose_name='якорь')),
                ('limit', models.PositiveSmallIntegerField(default=16, verbose_name='максимум навыков')),
                ('show_level', models.BooleanField(default=False, verbose_name='показывать уровень')),
            ],
            options={
                'verbose_name': 'сетка избранных навыков',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='HeroPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(blank=True, max_length=140, verbose_name='заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=240, verbose_name='подзаголовок')),
                ('intro', models.TextField(blank=True, max_length=600, verbose_name='вступительный текст')),
                ('show_terminal', models.BooleanField(default=True, verbose_name='показывать терминал')),
                ('terminal_command', models.CharField(default='whoami', max_length=80, verbose_name='команда в терминале')),
                ('primary_label', models.CharField(blank=True, max_length=60, verbose_name='текст основной кнопки')),
                ('primary_url', models.CharField(blank=True, max_length=200, verbose_name='ссылка основной кнопки')),
                ('secondary_label', models.CharField(blank=True, max_length=60, verbose_name='текст второй кнопки')),
                ('secondary_url', models.CharField(blank=True, max_length=200, verbose_name='ссылка второй кнопки')),
            ],
            options={
                'verbose_name': 'блок Hero',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='MiniProjectsPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('heading', models.CharField(blank=True, max_length=120, verbose_name='заголовок')),
                ('subheading', models.CharField(blank=True, max_length=240, verbose_name='подзаголовок')),
                ('anchor', models.SlugField(blank=True, help_text='Используется как id секции для навигации по странице.', max_length=60, verbose_name='якорь')),
                ('limit', models.PositiveSmallIntegerField(default=12, verbose_name='максимум мини-проектов')),
                ('show_all_link', models.BooleanField(default=True, verbose_name='ссылка на все мини-проекты')),
            ],
            options={
                'verbose_name': 'блок мини-проектов',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='порядок')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='название')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='slug')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'категория проектов',
                'verbose_name_plural': 'категории проектов',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='порядок')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='название')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'категория навыков',
                'verbose_name_plural': 'категории навыков',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='порядок')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='название')),
                ('url', models.URLField(verbose_name='ссылка')),
                ('icon', models.CharField(blank=True, max_length=60, verbose_name='иконка')),
                ('username', models.CharField(blank=True, max_length=80, verbose_name='username')),
                ('is_visible', models.BooleanField(default=True, verbose_name='отображать')),
            ],
            options={
                'verbose_name': 'социальная ссылка',
                'verbose_name_plural': 'социальные ссылки',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='SocialLinksPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('heading', models.CharField(blank=True, max_length=120, verbose_name='заголовок')),
                ('subheading', models.CharField(blank=True, max_length=240, verbose_name='подзаголовок')),
                ('anchor', models.SlugField(blank=True, help_text='Используется как id секции для навигации по странице.', max_length=60, verbose_name='якорь')),
                ('style', models.CharField(choices=[('icons', 'Только иконки'), ('cards', 'Карточки')], default='cards', max_length=10, verbose_name='оформление')),
            ],
            options={
                'verbose_name': 'блок социальных ссылок',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='порядок')),
                ('institution', models.CharField(max_length=160, verbose_name='учебное заведение')),
                ('program', models.CharField(max_length=160, verbose_name='программа')),
                ('degree', models.CharField(blank=True, max_length=120, verbose_name='степень')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('started_on', models.DateField(verbose_name='дата начала')),
                ('finished_on', models.DateField(blank=True, null=True, verbose_name='дата окончания')),
            ],
            options={
                'verbose_name': 'образование',
                'verbose_name_plural': 'образование',
                'ordering': ('order', '-started_on'),
                'constraints': [models.CheckConstraint(condition=models.Q(('finished_on__isnull', True), ('finished_on__gte', models.F('started_on')), _connector='OR'), name='education_finished_after_started')],
            },
        ),
        migrations.CreateModel(
            name='MiniProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='порядок')),
                ('title', models.CharField(max_length=120, verbose_name='название')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='slug')),
                ('summary', models.CharField(max_length=200, verbose_name='краткое описание')),
                ('url', models.URLField(verbose_name='ссылка')),
                ('icon', models.CharField(blank=True, max_length=60, verbose_name='иконка')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='активен')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mini_projects', to='portfolio.projectcategory', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'мини-проект',
                'verbose_name_plural': 'мини-проекты',
                'ordering': ('order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='FeaturedProjectsPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('heading', models.CharField(blank=True, max_length=120, verbose_name='заголовок')),
                ('subheading', models.CharField(blank=True, max_length=240, verbose_name='подзаголовок')),
                ('anchor', models.SlugField(blank=True, help_text='Используется как id секции для навигации по странице.', max_length=60, verbose_name='якорь')),
                ('limit', models.PositiveSmallIntegerField(default=6, verbose_name='максимум проектов')),
                ('only_featured', models.BooleanField(default=True, verbose_name='только избранные')),
                ('show_all_link', models.BooleanField(default=True, verbose_name='ссылка на все проекты')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='portfolio.projectcategory', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'блок избранных проектов',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='SkillCategoriesPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('heading', models.CharField(blank=True, max_length=120, verbose_name='заголовок')),
                ('subheading', models.CharField(blank=True, max_length=240, verbose_name='подзаголовок')),
                ('anchor', models.SlugField(blank=True, help_text='Используется как id секции для навигации по странице.', max_length=60, verbose_name='якорь')),
                ('categories', models.ManyToManyField(blank=True, help_text='Пусто — показываются все категории.', related_name='+', to='portfolio.skillcategory', verbose_name='категории')),
            ],
            options={
                'verbose_name': 'блок категорий навыков',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='порядок')),
                ('name', models.CharField(max_length=80, verbose_name='название')),
                ('icon', models.CharField(blank=True, help_text='Имя иконки из набора проекта, необязательно.', max_length=60, verbose_name='иконка')),
                ('level', models.CharField(blank=True, help_text='Свободная характеристика, например «продакшн» или «базовый».', max_length=60, verbose_name='уровень')),
                ('is_featured', models.BooleanField(default=False, verbose_name='показывать на главной')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='portfolio.skillcategory', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'навык',
                'verbose_name_plural': 'навыки',
                'ordering': ('category__order', 'order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='порядок')),
                ('seo_title', models.CharField(blank=True, max_length=70, verbose_name='SEO title')),
                ('seo_description', models.CharField(blank=True, max_length=200, verbose_name='SEO description')),
                ('title', models.CharField(max_length=140, verbose_name='название')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='slug')),
                ('summary', models.CharField(max_length=280, verbose_name='короткое описание')),
                ('description', models.TextField(blank=True, verbose_name='полное описание')),
                ('cover', models.ImageField(blank=True, upload_to='projects/', verbose_name='обложка')),
                ('cover_alt', models.CharField(blank=True, max_length=160, verbose_name='alt-текст обложки')),
                ('repository_url', models.URLField(blank=True, verbose_name='ссылка на репозиторий')),
                ('demo_url', models.URLField(blank=True, verbose_name='ссылка на демонстрацию')),
                ('source', models.CharField(choices=[('github', 'GitHub'), ('gitverse', 'GitVerse'), ('other', 'Другое')], default='github', max_length=20, verbose_name='источник')),
                ('status', models.CharField(choices=[('active', 'В разработке'), ('completed', 'Завершён'), ('archived', 'Архив')], db_index=True, default='active', max_length=20, verbose_name='статус')),
                ('started_on', models.DateField(blank=True, null=True, verbose_name='дата начала')),
                ('finished_on', models.DateField(blank=True, null=True, verbose_name='дата завершения')),
                ('is_open_source', models.BooleanField(default=True, verbose_name='open source')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='избранный')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='опубликован')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='portfolio.projectcategory', verbose_name='категория')),
                ('technologies', models.ManyToManyField(blank=True, related_name='projects', to='portfolio.skill', verbose_name='технологии')),
            ],
            options={
                'verbose_name': 'проект',
                'verbose_name_plural': 'проекты',
                'ordering': ('order', '-started_on', 'title'),
                'indexes': [models.Index(fields=['is_published', 'is_featured'], name='project_pub_featured_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('finished_on__isnull', True), ('started_on__isnull', True), ('finished_on__gte', models.F('started_on')), _connector='OR'), name='project_finished_after_started')],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='порядок')),
                ('organization', models.CharField(max_length=140, verbose_name='организация')),
                ('organization_url', models.URLField(blank=True, verbose_name='сайт организации')),
                ('position', models.CharField(max_length=140, verbose_name='должность')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('started_on', models.DateField(verbose_name='дата начала')),
                ('finished_on', models.DateField(blank=True, null=True, verbose_name='дата окончания')),
                ('is_current', models.BooleanField(default=False, verbose_name='текущее место работы')),
                ('technologies', models.ManyToManyField(blank=True, related_name='experiences', to='portfolio.skill', verbose_name='технологии')),
            ],
            options={
                'verbose_name': 'опыт работы',
                'verbose_name_plural': 'опыт работы',
                'ordering': ('order', '-started_on'),
                'constraints': [models.CheckConstraint(condition=models.Q(('finished_on__isnull', True), ('finished_on__gte', models.F('started_on')), _connector='OR'), name='experience_finished_after_started'), models.CheckConstraint(condition=models.Q(('is_current', False), ('finished_on__isnull', True), _connector='OR'), name='experience_current_has_no_end')],
            },
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='unique_skill_per_category'),
        ),
    ]
