# Generated by Django 5.2.16 on 2026-08-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='телефон'),
        ),
    ]
