# Generated by Django 5.2.16 on 2026-08-03 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0041_alter_pageurl_unique_together_pageurl_site_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CtaPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('heading', models.CharField(blank=True, max_length=120, verbose_name='заголовок')),
                ('subheading', models.CharField(blank=True, max_length=240, verbose_name='подзаголовок')),
                ('anchor', models.SlugField(blank=True, help_text='Используется как id секции для навигации по странице.', max_length=60, verbose_name='якорь')),
                ('text', models.TextField(blank=True, max_length=400, verbose_name='текст')),
                ('button_label', models.CharField(max_length=60, verbose_name='текст кнопки')),
                ('button_url', models.CharField(max_length=200, verbose_name='ссылка кнопки')),
                ('secondary_label', models.CharField(blank=True, max_length=60, verbose_name='текст второй кнопки')),
                ('secondary_url', models.CharField(blank=True, max_length=200, verbose_name='ссылка второй кнопки')),
            ],
            options={
                'verbose_name': 'блок призыва к действию',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Никита Колесников', max_length=120, verbose_name='название сайта')),
                ('tagline', models.CharField(blank=True, max_length=200, verbose_name='подзаголовок')),
                ('default_seo_title', models.CharField(blank=True, max_length=70, verbose_name='SEO title по умолчанию')),
                ('default_seo_description', models.CharField(blank=True, max_length=200, verbose_name='SEO description по умолчанию')),
                ('default_og_image', models.ImageField(blank=True, upload_to='site/', verbose_name='изображение Open Graph')),
                ('footer_text', models.CharField(blank=True, max_length=200, verbose_name='текст в подвале')),
                ('robots_extra', models.TextField(blank=True, help_text='Добавляются в конец сгенерированного robots.txt.', verbose_name='дополнительные строки robots.txt')),
                ('yandex_verification', models.CharField(blank=True, max_length=64, verbose_name='Yandex verification')),
                ('google_verification', models.CharField(blank=True, max_length=64, verbose_name='Google verification')),
            ],
            options={
                'verbose_name': 'настройки сайта',
                'verbose_name_plural': 'настройки сайта',
            },
        ),
    ]
