# Generated by Django 5.2.16 on 2026-08-03 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0041_alter_pageurl_unique_together_pageurl_site_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactBlockPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('heading', models.CharField(blank=True, max_length=120, verbose_name='заголовок')),
                ('subheading', models.CharField(blank=True, max_length=240, verbose_name='подзаголовок')),
                ('anchor', models.SlugField(blank=True, help_text='Используется как id секции для навигации по странице.', max_length=60, verbose_name='якорь')),
                ('text', models.TextField(blank=True, max_length=400, verbose_name='текст')),
                ('show_form', models.BooleanField(default=True, verbose_name='показывать форму')),
                ('show_social', models.BooleanField(default=True, verbose_name='показывать социальные ссылки')),
                ('show_email', models.BooleanField(default=True, verbose_name='показывать email')),
            ],
            options={
                'verbose_name': 'контактный блок',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('name', models.CharField(max_length=120, verbose_name='имя')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('subject', models.CharField(blank=True, max_length=160, verbose_name='тема')),
                ('message', models.TextField(max_length=4000, verbose_name='сообщение')),
                ('is_processed', models.BooleanField(db_index=True, default=False, verbose_name='обработано')),
                ('remote_addr', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='User-Agent')),
            ],
            options={
                'verbose_name': 'обращение',
                'verbose_name_plural': 'обращения',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['is_processed', '-created_at'], name='contact_processed_idx')],
            },
        ),
    ]
