# Generated by Django 5.2.16 on 2026-08-03 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0041_alter_pageurl_unique_together_pageurl_site_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='порядок')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='название')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='slug')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'категория статей',
                'verbose_name_plural': 'категории статей',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='название')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'тег',
                'verbose_name_plural': 'теги',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='LatestArticlesPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('heading', models.CharField(blank=True, max_length=120, verbose_name='заголовок')),
                ('subheading', models.CharField(blank=True, max_length=240, verbose_name='подзаголовок')),
                ('anchor', models.SlugField(blank=True, help_text='Используется как id секции для навигации по странице.', max_length=60, verbose_name='якорь')),
                ('limit', models.PositiveSmallIntegerField(default=3, verbose_name='максимум статей')),
                ('show_all_link', models.BooleanField(default=True, verbose_name='ссылка на все статьи')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'блок последних статей',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('seo_title', models.CharField(blank=True, max_length=70, verbose_name='SEO title')),
                ('seo_description', models.CharField(blank=True, max_length=200, verbose_name='SEO description')),
                ('title', models.CharField(max_length=200, verbose_name='заголовок')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('excerpt', models.TextField(max_length=400, verbose_name='превью')),
                ('body', models.TextField(verbose_name='текст статьи')),
                ('cover', models.ImageField(blank=True, upload_to='articles/', verbose_name='обложка')),
                ('cover_alt', models.CharField(blank=True, max_length=160, verbose_name='alt-текст обложки')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликована')], db_index=True, default='draft', max_length=20, verbose_name='статус')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='дата публикации')),
                ('reading_time', models.PositiveSmallIntegerField(default=0, help_text='0 — рассчитывается автоматически при отображении.', verbose_name='время чтения, мин')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='blog.category', verbose_name='категория')),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='blog.tag', verbose_name='теги')),
            ],
            options={
                'verbose_name': 'статья',
                'verbose_name_plural': 'статьи',
                'ordering': ('-published_at', '-created_at'),
                'indexes': [models.Index(fields=['status', 'published_at'], name='article_status_pub_idx')],
            },
        ),
    ]
