# Generated by Django 5.2.16 on 2026-08-13 20:05

import djangocms_text.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=djangocms_text.fields.HTMLField(verbose_name='текст статьи'),
        ),
    ]
